/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsEnum,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { Type } from "class-transformer";
import { EnumCustomizationTheme } from "./EnumCustomizationTheme";
import { EnumCustomizationTransitions } from "./EnumCustomizationTransitions";

@ObjectType()
class Customization {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  associatedReel!: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  backgroundMusic!: JsonValue;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reelCustomization!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumCustomizationTheme,
  })
  @IsEnum(EnumCustomizationTheme)
  @IsOptional()
  @Field(() => EnumCustomizationTheme, {
    nullable: true,
  })
  theme?: "Option1" | null;

  @ApiProperty({
    required: false,
    enum: EnumCustomizationTransitions,
    isArray: true,
  })
  @IsEnum(EnumCustomizationTransitions, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumCustomizationTransitions], {
    nullable: true,
  })
  transitions?: Array<"Option1">;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Customization as Customization };
