/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TextInputService } from "../textInput.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TextInputCreateInput } from "./TextInputCreateInput";
import { TextInput } from "./TextInput";
import { TextInputFindManyArgs } from "./TextInputFindManyArgs";
import { TextInputWhereUniqueInput } from "./TextInputWhereUniqueInput";
import { TextInputUpdateInput } from "./TextInputUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TextInputControllerBase {
  constructor(
    protected readonly service: TextInputService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TextInput })
  @nestAccessControl.UseRoles({
    resource: "TextInput",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTextInput(
    @common.Body() data: TextInputCreateInput
  ): Promise<TextInput> {
    return await this.service.createTextInput({
      data: data,
      select: {
        associatedReel: true,
        content: true,
        createdAt: true,
        id: true,
        reelReference: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TextInput] })
  @ApiNestedQuery(TextInputFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TextInput",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async textInputs(@common.Req() request: Request): Promise<TextInput[]> {
    const args = plainToClass(TextInputFindManyArgs, request.query);
    return this.service.textInputs({
      ...args,
      select: {
        associatedReel: true,
        content: true,
        createdAt: true,
        id: true,
        reelReference: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TextInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TextInput",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async textInput(
    @common.Param() params: TextInputWhereUniqueInput
  ): Promise<TextInput | null> {
    const result = await this.service.textInput({
      where: params,
      select: {
        associatedReel: true,
        content: true,
        createdAt: true,
        id: true,
        reelReference: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TextInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TextInput",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTextInput(
    @common.Param() params: TextInputWhereUniqueInput,
    @common.Body() data: TextInputUpdateInput
  ): Promise<TextInput | null> {
    try {
      return await this.service.updateTextInput({
        where: params,
        data: data,
        select: {
          associatedReel: true,
          content: true,
          createdAt: true,
          id: true,
          reelReference: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TextInput })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TextInput",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTextInput(
    @common.Param() params: TextInputWhereUniqueInput
  ): Promise<TextInput | null> {
    try {
      return await this.service.deleteTextInput({
        where: params,
        select: {
          associatedReel: true,
          content: true,
          createdAt: true,
          id: true,
          reelReference: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
